### ISSUE TITLE
Missing tau

### ISSUE THREAD

**Issue by SirRob1997** [lucidrains/cross-transformers-pytorch#1]
If I'm correct, the rescaling via `tau = self.dim_key**0.5` described in Eq.1 of the paper is missing after [L44](https://github.com/lucidrains/cross-transformers-pytorch/blob/main/cross_transformers_pytorch/cross_transformers_pytorch.py#L44).

**Comment by lucidrains** [comment]
oh yes, you are right! https://github.com/lucidrains/cross-transformers-pytorch/releases/tag/0.0.2
